version: '3'
services:

  server:
    image: "movies"
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  client:
    image: "moviesfrontend"
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - server